apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
# This config creates users, set passwords and create their folders. Everyone has own profile, with data folder in it. Users cant write to their home folder, only to the data subfolder. Passwords here must be encrypted.
# user0 is like admin user - has access to the whole home folder.
data:
  users.conf: |
    #{user0}#:#{user0_password}#:e:2000:100::/home
    #{user1}#:#{user1_password}#:e:1000:100::/home/#{user1}#
    #{user2}#:#{user2_password}#:e:1001:100::/home/#{user2}#
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
        elastic.skoda-auto.com/leanix_id: "32112" 
      annotations:  
        elastic.co/dataset: kubernetes.container_logs.keycloak.log  
        elastic.skoda-auto.com/cla-ingestion: multiline-generic 
    spec:
      containers:
        - name: sftp
          image: ghcr.io/zateckar/sftp-alpine:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3122
          resources:
              limits:
                memory: 128Mi
                cpu: 50m
          volumeMounts:
            - name: sftp-config
              mountPath: /etc/sftp/
              readOnly: true
            - name: sftp-data
              mountPath: /home
      volumes:
        - name: sftp-config
          configMap:
            name: user-config
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-data-claim
  triggers:
    - type: ConfigChange
---
kind: Service
apiVersion: v1
metadata:
  name: sftp-service
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: #{dns_label}#
    service.beta.kubernetes.io/port_3122_no_probe_rule: "true" # Heartbeat cannot be ssh and causes warnings, in this case it is no needed
spec:
  type: LoadBalancer
  ports:
    - name: ssh
      port: 3122   # Port from outside
      targetPort: 3122   # Port of the container
  selector:
    app: sftp
  externalTrafficPolicy: Local # Pass real client ip to pod
  loadBalancerSourceRanges:
  - 10.20.30.0/24
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: default
  resources:
    requests:
      storage: 200Mi  # As-is, minimum on AKS is 1GB
