name: Docker Image CI

on:
 workflow_dispatch
#   schedule:
#    - cron: '30 8 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push - Alpine
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sftp-alpine
          registry: ghcr.io
          tags: latest
          labels: alpine=latest
          dockerfile: ./Dockerfile-alpine
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: Build and push - Debian
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sftp-debian
          registry: ghcr.io
          tags: latest
          labels: debian=latest
          dockerfile: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
